### ISSUE TITLE
Ошика импорта на 120+ товарах

### ISSUE THREAD

**Issue by uptimizt** [uptimizt/wooms#1]
лог:
`PHP Fatal error: Cannot use object of type WP_Error as array in /home/i/intermtt/shop.ukr-opt.net/public_html/wp-content/plugins/wooms/inc/class-import-product-categories.php on line 73`

**Comment by artikus11** [comment]
Что-то не наблюдаю такого,  надо проверять

**Comment by uptimizt** [comment]
суть не в наблюдении на тесте. понятно что оно проявляется не всегда.
суть в том что условия не верно построено и его надо слегка перестроить. чтобы WPError правильно ловился.

**Comment by artikus11** [comment]
Ок, проверю
