### ISSUE TITLE
Ссылка на предложения и улучшения

### ISSUE THREAD

**Issue by uptimizt** [uptimizt/wooms#14]
нужно добавить ссылку на гитхаб ишью https://github.com/uptimizt/wooms/issues
в настройки

назвать типа "Предложения по улучшению и запросы на доработку"

код тут https://github.com/uptimizt/wooms/blob/master/inc/class-menu-settings.php#L177

добавить перед ссылкой на тех поддержку

**Comment by artikus11** [comment]
Ок. ща добавлю. Я там еще баг пофиксил небольшой. Версию плагина 2.0.9 делать или в 2.0.8 оставить?

**Comment by uptimizt** [comment]
да, лучше менять версию @artikus11

**Comment by uptimizt** [comment]
это не срочный тикет )

**Comment by artikus11** [comment]
@uptimizt Там фиг бага срочный был. Так что все сделал, ща реквест сделаю

**Comment by artikus11** [comment]
@uptimizt посмотри реквест https://github.com/uptimizt/wooms/pull/15
