### ISSUE TITLE
Переименовать WooMS Extra в WooMS XT

### ISSUE THREAD

**Issue by uptimizt** [uptimizt/wooms#17]
XT - сокращение от Extansion. Типа расширенная версия. Для краткости.
Надо переименовать это в ГитЛаб. Сообщить мне, далее я переименую страницы на wpcraft.ru

**Comment by artikus11** [comment]
Extentions может, тогда да будет расширенная)
Ок, только папку лучше не менять, проблемы могут быть. А остальное поменяю
