### ISSUE TITLE
Сделать функционал исключений категорий из синхронизации

### ISSUE THREAD

**Issue by artikus11** [uptimizt/wooms#21]
Так как, уже есть выбор нужной категории для синка, логично сделать исключение категории из синка.

**Comment by uptimizt** [comment]
не вижу логичности )
в других решениях от МойСклад я не видел такой опции. подозреваю что это будет дорого и сложно. нужно ясно понимать что иных путей решить эту задачу нет (например перенос групп внутри МойСклад или ограничение по складу)

**Comment by artikus11** [comment]
Ну я других решений не видел. Но обычно так и делают когда можно или выбрать нужную рубрику или исключить рубрики из синка. Как это технически сделать я пока плохо представляю... Думать надо

**Comment by uptimizt** [comment]
дубль https://github.com/uptimizt/wooms/issues/36
