### ISSUE TITLE
Как сделать синхронизацию доступных остатков?

### ISSUE THREAD

**Issue by ni032mas** [uptimizt/wooms#29]
Как сделать синхронизацию доступных остатков Woocommerce - МойСклад? Сейчас синхронизируются просто остатки не учитывая резерв. Мне кажется некоторое время назад синхронизировались остатки учитывая резерв. Речь идет о платной версии плагина.

**Comment by ni032mas** [comment]
Уважаемые разработчики, можете хоть что-то ответить. При покупке плагина обещалась техническая поддержка в течении года. Мною сделано два запроса и не на один нет ответа, решил уже здесь написать и в ответ опять тишина. Предупреждайте перед продажей плагина, что поддержки нет и не будет, работоспособность не гарантируем.

**Comment by uptimizt** [comment]
@artikus11 есть идеи как это можно решить?

**Comment by uptimizt** [comment]
на сколько помню там изначально мы берем либо остатки в целом по организации, либо в целом по складу. без учета каких либо резервов.
надо глянуть в документации к API, есть ли там такой фильтр и если есть то добавить как опцию.

**Comment by ni032mas** [comment]
Спасибо, что ответили. Ваш плагин получает остатки из атрибута **stock** отчета **ВСЕ ОСТАТКИ**, а хотелось бы, чтобы получал из **quantity**, ну или настройка какая-нибудь была откуда получать. И мне кажется, что раньше так и было, по крайней мере в июне, хотя плагин не обновляли. Мы столкнулись с проблемой заказов в минус только сейчас.

**Comment by artikus11** [comment]
Я правильно понимаю, речь про синхронизацию на сайте?

**Comment by uptimizt** [comment]
@artikus11 я думаю что тут речь о том что остатки вообще и остатки с учетом резерва это разные данные.

например у тебя 5 яблок на складе. но 2 зарезервировали клиент А и Б. а значит остатки на сайте должны быть 3 а не 5. хотя по складу их 5.

**Comment by artikus11** [comment]
@uptimizt А такой функционал разве есть в плагине? Скинь ссылку где код про это в плагине посмотреть

**Comment by uptimizt** [comment]
@artikus11 нет функционала такого. потому и тикет сделали. надо делать.

**Comment by artikus11** [comment]
@uptimizt Дак в тикете написано было что есть) Потому и спросил.
Буде делать тогда

**Comment by ni032mas** [comment]
@artikus11 Да, речь про синхронизацию на сайте. Товары используются обычные, не вариативные. Настройку синхронизации устанавливал и по складам и без складов. Временно решил свою проблему так, в классе **WooMS_Warehouses** в строке 42 и 46 заменил **stock** на **quantity**.

**Comment by artikus11** [comment]
@uptimizt Ты сделаешь?

@ni032mas Спасибо за фидбек, постараемся максимально быстро решить проблему

**Comment by uptimizt** [comment]
поправил. думаю так и должно работать по умолчанию.

но плюс сделал хук для управления этой опцией:

```
		/**
		 * Поле по которому берем остаток?
		 * quantity = это доступные остатки за вычетом резервов
		 * stock = это все остатки по организации
		 */
		$stock_type = apply_filters('wooms_stock_type', 'quantity');

```

сейчас опубликуем релизы.

**Comment by uptimizt** [comment]
@ni032mas спасибо за обратную связь.
обновили плагины. можно пробовать.

**Comment by 9652310** [comment]
здравствуйте! как изменить синхронизацию в настройках с 1 часа на 20 минут wooms, wooms-extra, если это можно сделать в файлах модуля то подскажите где и что добавить.

**Comment by OlaIola** [comment]
@9652310 В WooCommerce есть функция управления остатками и если ее включить, он автоматически будет корректировать остатки, поэтому синхронизацию нужно запускать так часто, как часто бывают приходы на склад. Склад для интернет-магазина, даже виртуальный, должен быть отдельным, тогда проблем с "заказали то, чего уже нет", не будет. 
А что касается синхронизации за 20 минут - ни факт, что она за это время будет доходить до конца, в зависимости от количества товаров минимальное время между циклами может быть нужно ставить даже больше часа.

**Comment by 9652310** [comment]
дело в том что мы работаем с маркет плейсами Ямаркет  и тд. если будет стоять синхронизация в 1 час, то пока произойдет следующая синхронизация этот товар уже снимут, на маркет плейсе дается время в 25 минут до следующего обновления, как быть?

**Comment by 9652310** [comment]
дело в том что мы работаем с маркет плейсами Ямаркет и тд. если будет
стоять синхронизация в 1 час, то пока произойдет следующая синхронизация
этот товар уже снимут, на маркет плейсе дается время в 25 минут до
следующего обновления, как быть? Прикрепляю скрины с настройками ниже
*------------------------------------------------------------------------------------------------*
*C уважением Николай!*

*Разработка, создание, техническая поддержка и продвижение сайтов любой
сложности по доступным ценам. Профессионально, в срок!*

Тел.: +7 (909) 965 23 10

Skype: niks-80

E-mail: ***@***.***


вт, 15 июн. 2021 г. в 10:58, Olga Gleckler ***@***.***>:

**Comment by OlaIola** [comment]
Маркет проверят актуальные остатки на сайте и делает периодически контрольные заказе. У вас включено управление остатками в WooCommerce? Если да - то все должно быть в порядке, хотя нужно смотреть еще на кеширование.

**Comment by 9652310** [comment]
![1](https://user-images.githubusercontent.com/74200206/122020213-3ff5df80-cdcd-11eb-8141-15978b5ccd2b.png)
![2](https://user-images.githubusercontent.com/74200206/122020251-48e6b100-cdcd-11eb-9aa8-50c497058d37.png)
![3](https://user-images.githubusercontent.com/74200206/122020259-4a17de00-cdcd-11eb-8380-e9b1c3ca746c.png)
![4](https://user-images.githubusercontent.com/74200206/122020261-4a17de00-cdcd-11eb-84f5-2c4f445ad58a.png)
![5](https://user-images.githubusercontent.com/74200206/122020263-4ab07480-cdcd-11eb-8454-c1b8f0eed3ab.png)
![6](https://user-images.githubusercontent.com/74200206/122020266-4ab07480-cdcd-11eb-9fbf-bcdab9387e7a.png)

**Comment by 9652310** [comment]
так как мне сделать чтоб синхронизация на маркетплейсе проходила за 20 минут а не за час?

**Comment by 9652310** [comment]
Для drupal 8 у вас есть решение, синхронизации с Мой склад?

**Comment by OlaIola** [comment]
1. У вас включено управление остатками в WooCommerce? Если да - проблемы нет, если нет - включите управление остатками. 
2. Если выгрузки в ЯМаркет кешируются - исключите их из кеширования.
3. Для Drupal решения нет.

**Comment by 9652310** [comment]
1. Да включено
2. Что касается кеширования то кеширование на сайте нет, модуль не вкл для кеширования сайта
![1](https://user-images.githubusercontent.com/74200206/122023627-65d0b380-cdd0-11eb-8263-a94f5aa9f0e9.png)

**Comment by OlaIola** [comment]
1. Если включено:
![2021-06-15_12-05-45](https://user-images.githubusercontent.com/16874687/122025591-c3153680-cdc9-11eb-9231-0589376374c9.png)
то WooCommerce сам управляет остатками. Сделали заказ 1 последней штуки в наличии - станет 0 и статус "out of stock".  

Частая синхронизация со складом не нужна. От частоты зависит то, как часто новые поступления будут попадать на сайт. со склада и это вполне может быть несколько раз в сутки (в зависимости от того, как часто склад осуществляет приемку).

**Comment by 9652310** [comment]
мне надо указать удержание запаса 20 минут? я правильно понял? сейчас стоит 60 мин

**Comment by OlaIola** [comment]
Эта опция бронирует товар на сайте за покупателем на это время, т.е. за это время он должен быть оплачен, а если нет - снова станет доступны для заказа. Вам виднее, решает ли это задачу, но 60 минут действительно много. Если человек не оплатил за 20 минут заказ, то вряд ли уже оплатит, и разумно быстрей вернуть товар в продажу.

**Comment by 9652310** [comment]
ок, спасибо я вам напишу еще, возможно будут еще вопросы

**Comment by 9652310** [comment]
посоветовался с руководством и все таки нам немного не то что вы думаете надо, вы немного недопоняли что нужно нам, про запасы забудьте, запасы это на стороне сайта в админке или на стороне сервиса Мой склад, нам нужно чтоб синхронизация проходила в 20 минут а не в 1час... Меня интересует как и где в коде модуля можно добавить или изменить опцию синхронизации не по часам а по минутам, какой фрагмент и где отвечает в коде за это, чтоб при выборе в списке можно было выставить синхронизацию не только в часах но и в минутах или все в минутах.

**Comment by 9652310** [comment]
и еще, а если выключить опцию "Включить синхронизацию продуктов по расписанию", расписание можно будет только в ручную запускать или что произойдет?

**Comment by OlaIola** [comment]
1. Сколько у вас товаров (с вариациями) ?
2. Чего нужно добиться в результате?

**Comment by 9652310** [comment]
1. товаров 1663
2. Нужно чтоб в настройках модуля был выбор не только по часам но и по минутам, например минимальная синхронизация 20мин

**Comment by OlaIola** [comment]
2. Зачем, чего нужно добиться?

**Comment by 9652310** [comment]
нужна синхронизация 20 минут

**Comment by 9652310** [comment]
для маркетплейсов, потестить получится неполучится

**Comment by OlaIola** [comment]
Маркет забирает актуальные остатки товаров, если выгрузка для Маркета не кешируется, но они всегда актуальные.

**Comment by 9652310** [comment]
вы можете сделать под наши нужды такое и скинуть на почту? Сделать выбор в списке как есть и добавить синхронизацию в 20 мнут

**Comment by 9652310** [comment]
есть каталог Бумага/Фотобумага, в нем есть категории (Роллы фотобумага | 10×15 фотобумага | 13×18 фотобумага | A3 фотобумага | A4 фотобумага | A5 фотобумага),  есть и другие такие как Этикетки/Риббоны, но у них нет подкатегорий, на скрине подписал (НЕТ), при импорте с Мсклада все попадает в корень раздела каталога без распределения по категориям, в ЛК Мсклад все как надо, ниже скрины
![1](https://user-images.githubusercontent.com/74200206/122052279-2f099600-cdee-11eb-8b48-b24a3c9d770c.png)
![2](https://user-images.githubusercontent.com/74200206/122052284-303ac300-cdee-11eb-9e1d-e26c48deb3f9.png)
![3](https://user-images.githubusercontent.com/74200206/122052285-30d35980-cdee-11eb-805f-494f66438f21.png)
