### ISSUE TITLE
Проверка текущей версии WooMS XT через WooMS 

### ISSUE THREAD

**Issue by uptimizt** [uptimizt/wooms#30]
в WooMS в коммент где название плагина надо добавить параметр: Latest WooMS XT: 2.01

и далее в WooMS XT проверять этот параметр свяретья с текущей версией и если есть отрыв то сообщать что вышла новая версия WooMS XT.

делать это только на странице plugins. не стоит такое вешать на admin init

**Comment by artikus11** [comment]
Принято. Пока не знаю как это делать, надо думать и гуглить

**Comment by uptimizt** [comment]
@artikus11 вот метод https://developer.wordpress.org/reference/functions/get_plugin_data/

добавляем в коммент на старте плагина параметр `Latest WooMS XT: 2.0.1`
далее вызываем метод, он показывает нам что `data['Latest WooMS XT'] = '2.0.1'`
делаем сверку версий и если отстаем то сообщаем.

ты вроде бы делал уже нечто похожее

**Comment by artikus11** [comment]
А ну если так, то делал. Тогда без проблем

**Comment by uptimizt** [comment]
@artikus11 поздняк. уже сделал )

**Comment by artikus11** [comment]
@uptimizt ОК, ща пул сделаю

**Comment by uptimizt** [comment]
см историю
https://github.com/uptimizt/wooms/issues/30#ref-commit-b244ce8

@artikus11

**Comment by artikus11** [comment]
@uptimizt  Ок, я ддумал это в платном сделано. Все норм, запулил

**Comment by uptimizt** [comment]
![image](https://user-images.githubusercontent.com/1852897/44618355-e0756080-a87c-11e8-95a2-e69c90626c68.png)

@artikus11 зацени какой красивый костыль ))

**Comment by artikus11** [comment]
@uptimizt Ага, как раза смотрю. 
А чего не стандартную верстку использовал 
![image](https://user-images.githubusercontent.com/16116688/44618394-f3d8f980-a885-11e8-918b-9672285f2a46.png)

**Comment by uptimizt** [comment]
@artikus11 стандартная верстка срабатывает только если доступно стандартное обновление.
а это какой то более сложный механизм. там похоже несколько хуков надо использовать.
в лоб пытался вытащить, но не сработало, тк система считала что обновления нет.
и в общем пока как то сложновато.
потому сделал решение проще.

а потом наверное в идеале надо сделать как то правильней. чтобы уведомление о обновлении было не только в списке плагинов, но и в тулбаре с дашбордом.

**Comment by artikus11** [comment]
@uptimizt Вот так можно хтмл поправить
![image](https://user-images.githubusercontent.com/16116688/44618455-26372680-a887-11e8-8c4f-625d5f9709a3.png)

**Comment by uptimizt** [comment]
это костыль какой то ) ну его нафиг. надо просто использовать стандартные рекомендации и не изобретать велосипеды.
либо сообщение об обновлении либо доп row

**Comment by artikus11** [comment]
Это и есть стандартное, я просто скопировал хтмл из админки)

**Comment by uptimizt** [comment]
я визуально вижу рамки, которых не бывает если это стандартное

**Comment by artikus11** [comment]
Ну вот рамка только верхняя. Ладно, путь пока так. Все лучше чем ничего

**Comment by artikus11** [comment]
Оставлю тут ссылку https://rudrastyh.com/wordpress/self-hosted-plugin-update.html
Дойдут руки сделаем автоапдейт
