### ISSUE TITLE
Дубли категорий из за отличий в символах (е и ё)

### ISSUE THREAD

**Issue by uptimizt** [uptimizt/wooms#32]
# Проблема
был категория, которая уже оформлена и вроде бы она должна была связаться.
![image](https://user-images.githubusercontent.com/1852897/44616435-308dfc00-a858-11e8-9377-813b7593b586.png)

но почему то плагин не сумел ее распознать и создал дубль:
![image](https://user-images.githubusercontent.com/1852897/44616441-44d1f900-a858-11e8-92db-8deb24f340c8.png)

если приглядеться то разница в букве е и ё.

надо придумать как быть в таких ситуациях.

тк удаление категории в лоб в данном случае плохое решение. птм что уже есть контент и его перезабитие мб дорого стоить.

**Comment by uptimizt** [comment]
есть 2 решения:
# 1 удалить все дубли и сделать синк по новой 

если терять нечего, то можно просто удалить все категории и повторить обмен. 
самое простое решение.

# 2 удалить ошибочный дубль
если надо сохранить старый контент, то можно удалить ошибочный дубль.
перед этим сохранить его слаг и наименование.
после удаления надо его слаг и наименование назначить старой категории.
после этого плагин распознает нужную категорию и сделает связку.

для п 2 могут быть пробелмы с кешем. кеш лучше отключить на время этой операции или сбросить его после удаления дубля

**Comment by artikus11** [comment]
Проблема  в слаге. Слаги разные значит и категории разные. И получается что это не дубли, а разные категории. И связаться  категории смогут если слаги будут одинаковые. 
А как название рубрики выглядит в МС?
