### ISSUE TITLE
Ошибка использования хука plugins_loaded

### ISSUE THREAD

**Issue by uptimizt** [uptimizt/wooms#33]
вот это плохое решение:

add_action( 'plugins_loaded', 'wooms_check_php_and_wp_version' );

1. оно срабатывает на сайте, а должно срабатывать только в админке
2. по этой причине происходит излишняя нагрузка на сайт
3. по этой причине мы ловим фатал и вынуждены подключать лишние механики через 			`require_once ABSPATH . '/wp-admin/includes/plugin.php';`

**Comment by artikus11** [comment]
С чего бы? `plugins_loaded ` срабатывает раньше [всех остальных хуков](https://wp-kama.ru/hook/plugins_loaded) и ему пополам админка это или фронт
А `require_once ABSPATH . '/wp-admin/includes/plugin.php'; ` нужно для того чтобы данные получить и ошибку не выбивало, так как хук `plugins_loaded `  рано срабатывает 

Как по другому проверить и версию и наличие плагинов нужных?

**Comment by uptimizt** [comment]
1. ему понятно что пополам. мне не пополам и тем у кого лишняя нагрузка появляется там где не должно быть ее.
2. я понимаю зачем оно нужно. я не понимаю зачем эту херабасину тащить на сайт и устраивать там тормоза?

надо правильно использовать хуки и только там где это оправданно. нельзя брать и админский функционал без причины тащить на сайт создавая избыточную нагрузку там где ее быть не должно.

не надо по другому проверять версии плагина. сам механизм правильный. 
не правильно только хук используется. я уже поправил.

@artikus11

**Comment by uptimizt** [comment]
https://github.com/uptimizt/wooms/commit/ae8bd4e27f0ad91242f83ca43e521e9c831ef811

**Comment by artikus11** [comment]
А как ты разделяешь админкий хук и не админский?

**Comment by uptimizt** [comment]
> А как ты разделяешь админкий хук и не админский?

plugins loaded & init - это общесистемные хуки. сюда можно вешать только минимальные нагрузки.

если туда можно что то не вешать - значит вешать туда это нельзя не в коем случае.

проверку версий плагинов можно туда не вешать? можно. значит нельзя их туда вешать.

а где нам нужна проверка версии? только в админке. значит это хуки admin_init или admin_notice. это админские хуки. они срабатывают только в админке и не нагружают сайт.

@artikus11

**Comment by artikus11** [comment]
Теперь понятно, еще много чего я не совсем понимаю. Спасибо
